#datasource
spring:
  datasource:
    url: jdbc:mysql://120.76.136.204:3306/examsys
    username: root
    password: Zwh020716
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

